project_id = "alzyzfjzwvofmjccirjq"

[functions.grok-chat]
verify_jwt = true

[functions.xai-chat-assistant]
verify_jwt = true

[functions.ai-worker]
verify_jwt = false

[functions.ai-worker-cron]
verify_jwt = false

[functions.cleanup-deleted-users]
verify_jwt = true

[functions.sync-fan-emails]
verify_jwt = true

[functions.sync-management-emails]
verify_jwt = true

[functions.sync-profile-to-auth]
verify_jwt = true

[functions.cleanup-unverified-accounts]
verify_jwt = true

[functions.sync-user-emails]
verify_jwt = true

[functions.verify-user-email]
verify_jwt = true

[functions.delete-pending-user]
verify_jwt = true